# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Yale Jewelers
description: "Fine Jewelry, Estate, Custom Design and Repairs"
url: "http://www.yalejewelers.com"

twitter:
username: YaleJewelers

logo: /img/logo.jpg

google_site_verification: lAKceyEMLoLv1e4Sqk0mJUv7B2Eu3PP-fv5_DxJKpow

repository: techtangent/yalejewelers.com

# Build settings
markdown: kramdown
sass:
  style: compressed

gems:
- jekyll-seo-tag
- jekyll-sitemap

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      description: "Fine Jewelry, Estate, Custom Design and Repairs"
      order: 0
      carousel: ""

